name: deliveryapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  animated_snack_bar: ^0.3.1
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dialogs: ^0.0.7
  flutter_native_splash: ^2.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_ringtone_player: ^3.2.0
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  jiffy: ^6.2.1
  lottie: ^2.6.0
  rating_dialog: ^2.0.4
  shared_preferences: ^2.2.0

dev_dependencies:
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
  android_gravity: fill
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
